@extends('layouts.app')
@section('title', 'Tugas Harian')
@section('header', 'Tugas Harian')
@section('subtitle', 'Assign dan pantau checklist pekerjaan petugas')
@section('content')
<div class="page-header"><div><h2>Tugas Harian</h2><p>Filter tugas berdasarkan tanggal, status, area, atau petugas.</p></div><a href="{{ route('daily-tasks.create') }}" class="btn-primary">Assign Tugas</a></div>
<div class="filter-card"><form method="GET" class="filter-grid"><div class="form-field"><label>Tanggal</label><input type="date" name="task_date" value="{{ request('task_date') }}" class="form-control"></div><div class="form-field"><label>Status</label><select name="status" class="form-control"><option value="">Semua</option>@foreach($statuses as $value => $label)<option value="{{ $value }}" @selected(request('status') === $value)>{{ $label }}</option>@endforeach</select></div><div class="form-field"><label>Area</label><input name="area" value="{{ request('area') }}" class="form-control" placeholder="Cari area"></div><div class="form-field"><label>Petugas</label><select name="employee_id" class="form-control"><option value="">Semua</option>@foreach($employees as $employee)<option value="{{ $employee->id }}" @selected((string) request('employee_id') === (string) $employee->id)>{{ $employee->name }}</option>@endforeach</select></div><button class="btn-primary" type="submit">Filter</button><a class="btn-secondary" href="{{ route('daily-tasks.index') }}">Reset</a></form></div>
<div class="table-card"><div class="table-header"><div><h3>Daftar Tugas</h3><p>Data terbaru tampil paling atas.</p></div></div><div class="table-responsive"><table class="app-table"><thead><tr><th>Tanggal</th><th>Petugas</th><th>Area</th><th>Tugas</th><th>Status</th><th>Selesai</th><th>Aksi</th></tr></thead><tbody>
@forelse($dailyTasks as $task)<tr><td>{{ $task->task_date->format('d/m/Y') }}</td><td><strong>{{ $task->employee->name }}</strong><br><span class="text-muted">{{ $task->employee->employee_code }}</span></td><td>{{ $task->area ?: '-' }}</td><td><strong>{{ $task->title }}</strong><br><span class="text-muted">{{ Str::limit($task->description, 60) }}</span></td><td><span class="status-badge {{ $task->statusBadgeClass() }}">{{ $task->statusLabel() }}</span></td><td>{{ $task->completed_at?->format('H:i') ?? '-' }}</td><td><div class="form-actions" style="margin:0;gap:8px;"><a href="{{ route('daily-tasks.edit', $task) }}" class="btn-secondary">Edit</a>@unless($task->isCompleted())<form method="POST" action="{{ route('daily-tasks.mark-completed', $task) }}">@csrf<button class="btn-secondary" type="submit">Selesai</button></form>@endunless<form method="POST" action="{{ route('daily-tasks.destroy', $task) }}" onsubmit="return confirm('Hapus tugas ini?')">@csrf @method('DELETE')<button class="btn-secondary" type="submit">Hapus</button></form></div></td></tr>@empty<tr><td colspan="7" class="text-muted" style="text-align:center;padding:42px;">Belum ada tugas harian.</td></tr>@endforelse
</tbody></table></div>{{ $dailyTasks->links() }}</div>
@endsection
